In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Datasets ml/telecom_churn.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243553 entries, 0 to 243552
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   customer_id           243553 non-null  int64
 1   telecom_partner       243553 non-null  object
 2   gender                243553 non-null  object
 3   age                   243553 non-null  int64
 4   state                 243553 non-null  object
 5   city                  243553 non-null  object
 6   pincode               243553 non-null  int64
 7   date_of_registration  243553 non-null  object
 8   num_dependents        243553 non-null  int64
 9   estimated_salary      243553 non-null  int64
 10  calls_made            243553 non-null  int64
 11  sms_sent              243553 non-null  int64
 12  data_used             243553 non-null  int64
 13  churn                 243553 non-null  int64
dtypes: int64(9), object(5)
memory usage: 26.0+ MB

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop("churn",axis=1)
y = df["churn"]

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=df["churn"]
)

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 194842 entries, 20207 to 163921
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   customer_id           194842 non-null  int64
 1   telecom_partner       194842 non-null  object
 2   gender                194842 non-null  object
 3   age                   194842 non-null  int64
 4   state                 194842 non-null  object
 5   city                  194842 non-null  object
 6   pincode               194842 non-null  int64
 7   date_of_registration  194842 non-null  object
 8   num_dependents        194842 non-null  int64
 9   estimated_salary      194842 non-null  int64
 10  calls_made            194842 non-null  int64
 11  sms_sent              194842 non-null  int64
 12  data_used             194842 non-null  int64
dtypes: int64(8), object(5)
memory usage: 20.8+ MB

In [ ]:
X_train.isnull().sum()

customer_id             0
telecom_partner         0
gender                  0
age                     0
state                   0
city                    0
pincode                 0
date_of_registration    0
num_dependents          0
estimated_salary        0
calls_made              0
sms_sent                0
data_used               0
dtype: int64

In [ ]:
y_train.info()

<class 'pandas.core.series.Series'>
Index: 194842 entries, 20207 to 163921
Series name: churn
Non-Null Count   Dtype
--------------   -----
194842 non-null  int64
dtypes: int64(1)
memory usage: 3.0 MB

In [ ]:
y_train.value_counts()

churn
0    155780
1     39062
Name: count, dtype: int64

In [ ]:
num_columns = X.select_dtypes(include = ["int64","float64"]).columns
cat_columns = X.select_dtypes(include = ["object"]).columns

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

num = Pipeline([
    ("imputer",SimpleImputer(strategy = "median")),
    ("scaler", StandardScaler())
])

cat = Pipeline([
    ("imputer", SimpleImputer(strategy = "most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", num, num_columns),
    ("cat", cat, cat_columns)
])

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [ ]:
full_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("modeling", LogisticRegression())
])

In [ ]:
full_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['customer_id', 'age', 'pincode', 'num_dependents', 'estimated_salary',
       'calls_made', 'sms_sent', 'data_used'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['telecom_partner', 'gender', 'state', 'city', 'date_of_registration'], dtype='object'))])),
                ('modeling', LogisticRegression())])

In [ ]:
y_pred = full_pipeline.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, y_pred))

0.7995319332388988

In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[38946     0]
 [ 9765     0]]

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89     38946
           1       0.00      0.00      0.00      9765

    accuracy                           0.80     48711
   macro avg       0.40      0.50      0.44     48711
weighted avg       0.64      0.80      0.71     48711

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(full_pipeline, X_train, y_train, cv=5)
print(scores.mean())

0.7995196108879011